import { useI18n } from '../../i18n';

const advancedMessages = {
  ru: {
    common: {
      title: 'Wave C / Advanced',
      retry: 'Повторить',
      refresh: 'Обновить',
      save: 'Сохранить',
      create: 'Создать',
      loadingTitle: 'Загрузка данных',
      loadingDescription: 'Подтягиваем актуальное состояние из backend API.',
      errorTitle: 'Не удалось загрузить данные',
      errorDescription: 'Проверьте соединение и повторите попытку.',
      details: 'Детали',
      version: 'Версия',
      plannedTime: 'План',
      dueTime: 'Срок',
      priority: 'Приоритет',
      status: 'Статус',
      type: 'Тип',
      traceId: 'Trace ID',
      goal: 'Цель',
      task: 'Задача',
      openGoal: 'Открыть цель',
      openTask: 'Открыть задачу',
      noDescription: 'Описание пока не заполнено.',
      share: 'Совместно',
      language: 'Язык',
      enabled: 'Включено',
      disabled: 'Выключено',
      conflictTitle: 'Обнаружен конфликт версии',
      conflictDescription: 'Настройки успели измениться в другом сеансе. Мы подтянули свежую версию.',
      saved: 'Изменения сохранены.',
    },
    api: {
      validation_error: 'Проверьте заполнение формы.',
      conflict: 'Данные устарели и были обновлены.',
      unauthorized: 'Сеанс больше не действителен.',
      forbidden: 'Для этого действия недостаточно прав.',
      not_found: 'Запись больше недоступна.',
      internal_error: 'Сервер временно недоступен.',
      fallback: 'Не удалось выполнить запрос. Попробуйте еще раз.',
    },
    enums: {
      status: {
        todo: 'Новая',
        in_progress: 'В работе',
        done: 'Готово',
        cancelled: 'Отменена',
      },
      type: {
        green: 'Зеленая',
        red: 'Красная',
      },
      invitationStatus: {
        pending: 'Ожидает',
        accepted: 'Принято',
        declined: 'Отклонено',
        revoked: 'Отозвано',
      },
      thresholdPreset: {
        day: 'День',
        week: 'Неделя',
        month: 'Месяц',
      },
      quickPreset: {
        '30m': '+30 мин',
        '1h': '+1 час',
        '3h': '+3 часа',
        '24h': '+24 часа',
      },
      yes: 'Да',
      no: 'Нет',
    },
    calendar: {
      title: 'Календарь',
      subtitle: 'Простая проекция задач по времени с переносом и быстрым reschedule без выхода из защищенной оболочки.',
      rangeLabel: 'Диапазон',
      rangeDay: 'День',
      rangeWeek: 'Неделя',
      rangeMonth: 'Месяц',
      listTitle: 'Плановые задачи',
      listEmptyTitle: 'В выбранном диапазоне нет задач',
      listEmptyDescription: 'Когда у задач появится planned time, они будут показаны здесь.',
      detailTitle: 'Карточка задачи',
      moveTitle: 'Перенос времени',
      moveAction: 'Перенести',
      quickRescheduleTitle: 'Быстрый перенос',
      movedNotice: 'Плановое время обновлено.',
      rescheduledNotice: 'Быстрый перенос выполнен.',
      priorityDecayApplied: 'Priority decay был применен.',
      missingSelection: 'Выберите задачу слева, чтобы увидеть детали и действия.',
    },
    sharing: {
      title: 'Совместный доступ',
      subtitle: 'Инвайты и обзор shared resources без расширения scope до folder sharing.',
      inviteTitle: 'Новый инвайт',
      inviteTarget: 'Что открыть для доступа',
      inviteEmail: 'Email участника',
      inviteGoal: 'Цель',
      inviteTask: 'Задача',
      folderLabel: 'Папка',
      goalLabel: 'Цель',
      taskLabel: 'Задача',
      createInvite: 'Отправить инвайт',
      invitationListTitle: 'Инвайты',
      invitationsEmptyTitle: 'Инвайтов пока нет',
      invitationsEmptyDescription: 'После отправки приглашения или входящего share оно появится здесь.',
      resourcesTitle: 'Shared resources',
      sharedGoals: 'Shared goals',
      sharedTasks: 'Shared tasks',
      resourcesEmptyTitle: 'Общие ресурсы пока не обнаружены',
      resourcesEmptyDescription: 'После принятия инвайтов здесь появятся цели и задачи с доступом.',
      accept: 'Принять',
      decline: 'Отклонить',
      revoke: 'Отозвать',
      createdNotice: 'Инвайт отправлен.',
      updatedNotice: 'Статус инвайта обновлен.',
      targetHint: 'Можно открыть цель или отдельную задачу, без folder sharing.',
    },
    settings: {
      title: 'Настройки',
      subtitle: 'Язык интерфейса, уведомления и правила priority decay владельца.',
      generalTitle: 'Общие настройки',
      policyTitle: 'Правила priority decay',
      notificationsLabel: 'Push-уведомления',
      greenPolicy: 'Green policy',
      redPolicy: 'Red policy',
      threshold: 'Порог',
      decayAmount: 'Снижение приоритета',
      syncHint: 'Сохраненный язык сразу синхронизируется с активной web-локалью.',
      saveAction: 'Сохранить настройки',
    },
  },
  en: {
    common: {
      title: 'Wave C / Advanced',
      retry: 'Retry',
      refresh: 'Refresh',
      save: 'Save',
      create: 'Create',
      loadingTitle: 'Loading data',
      loadingDescription: 'Fetching the latest state from the backend API.',
      errorTitle: 'Could not load data',
      errorDescription: 'Please check the connection and try again.',
      details: 'Details',
      version: 'Version',
      plannedTime: 'Planned',
      dueTime: 'Due',
      priority: 'Priority',
      status: 'Status',
      type: 'Type',
      traceId: 'Trace ID',
      goal: 'Goal',
      task: 'Task',
      openGoal: 'Open goal',
      openTask: 'Open task',
      noDescription: 'Description is empty so far.',
      share: 'Shared',
      language: 'Language',
      enabled: 'Enabled',
      disabled: 'Disabled',
      conflictTitle: 'Version conflict detected',
      conflictDescription: 'The settings changed in another session. The latest version has been reloaded.',
      saved: 'Changes were saved.',
    },
    api: {
      validation_error: 'Please review the form fields.',
      conflict: 'The data was stale and has been refreshed.',
      unauthorized: 'The session is no longer valid.',
      forbidden: 'You do not have permission for this action.',
      not_found: 'The record is no longer available.',
      internal_error: 'The server is temporarily unavailable.',
      fallback: 'Request failed. Please try again.',
    },
    enums: {
      status: {
        todo: 'Todo',
        in_progress: 'In progress',
        done: 'Done',
        cancelled: 'Cancelled',
      },
      type: {
        green: 'Green',
        red: 'Red',
      },
      invitationStatus: {
        pending: 'Pending',
        accepted: 'Accepted',
        declined: 'Declined',
        revoked: 'Revoked',
      },
      thresholdPreset: {
        day: 'Day',
        week: 'Week',
        month: 'Month',
      },
      quickPreset: {
        '30m': '+30 min',
        '1h': '+1 hour',
        '3h': '+3 hours',
        '24h': '+24 hours',
      },
      yes: 'Yes',
      no: 'No',
    },
    calendar: {
      title: 'Calendar',
      subtitle: 'Simple time-based projection with move and quick reschedule actions inside the protected shell.',
      rangeLabel: 'Range',
      rangeDay: 'Day',
      rangeWeek: 'Week',
      rangeMonth: 'Month',
      listTitle: 'Scheduled tasks',
      listEmptyTitle: 'No tasks in this range',
      listEmptyDescription: 'Tasks appear here once they have a planned time.',
      detailTitle: 'Task card',
      moveTitle: 'Move time',
      moveAction: 'Move',
      quickRescheduleTitle: 'Quick reschedule',
      movedNotice: 'Planned time was updated.',
      rescheduledNotice: 'Quick reschedule completed.',
      priorityDecayApplied: 'Priority decay was applied.',
      missingSelection: 'Select a task on the left to see details and actions.',
    },
    sharing: {
      title: 'Sharing',
      subtitle: 'Invitations and shared-resource discovery without expanding scope into folder sharing.',
      inviteTitle: 'New invitation',
      inviteTarget: 'What to share',
      inviteEmail: 'Participant email',
      inviteGoal: 'Goal',
      inviteTask: 'Task',
      folderLabel: 'Folder',
      goalLabel: 'Goal',
      taskLabel: 'Task',
      createInvite: 'Send invitation',
      invitationListTitle: 'Invitations',
      invitationsEmptyTitle: 'No invitations yet',
      invitationsEmptyDescription: 'Sent or incoming shares will appear here.',
      resourcesTitle: 'Shared resources',
      sharedGoals: 'Shared goals',
      sharedTasks: 'Shared tasks',
      resourcesEmptyTitle: 'No shared resources found yet',
      resourcesEmptyDescription: 'Accepted invitations will surface shared goals and tasks here.',
      accept: 'Accept',
      decline: 'Decline',
      revoke: 'Revoke',
      createdNotice: 'Invitation sent.',
      updatedNotice: 'Invitation status updated.',
      targetHint: 'You can share a goal or an individual task, without folder sharing.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Interface language, notifications, and owner priority decay rules.',
      generalTitle: 'General settings',
      policyTitle: 'Priority decay rules',
      notificationsLabel: 'Push notifications',
      greenPolicy: 'Green policy',
      redPolicy: 'Red policy',
      threshold: 'Threshold',
      decayAmount: 'Decay amount',
      syncHint: 'The saved language is synchronized with the active web locale immediately.',
      saveAction: 'Save settings',
    },
  },
} as const;

export function useAdvancedCopy() {
  const { locale } = useI18n();
  return advancedMessages[locale];
}

