import { useI18n } from '../../i18n';

const advancedMessages = {
  ru: {
    common: {
      title: 'Рабочее пространство',
      retry: 'Повторить',
      refresh: 'Обновить',
      save: 'Сохранить',
      create: 'Создать',
      loadingTitle: 'Загрузка данных',
      loadingDescription: 'Подтягиваем актуальные данные.',
      errorTitle: 'Не удалось загрузить данные',
      errorDescription: 'Проверьте соединение и повторите попытку.',
      details: 'Детали',
      version: 'Версия',
      plannedTime: 'План',
      dueTime: 'Срок',
      priority: 'Приоритет',
      status: 'Статус',
      type: 'Тип',
      goal: 'Цель',
      task: 'Задача',
      openGoal: 'Открыть цель',
      openTask: 'Открыть задачу',
      noDescription: 'Описание пока не заполнено.',
      share: 'Общий доступ',
      language: 'Язык',
      enabled: 'Включено',
      disabled: 'Выключено',
      conflictTitle: 'Обнаружен конфликт версии',
      conflictDescription: 'Настройки успели измениться в другом окне. Мы подтянули свежую версию.',
      saved: 'Изменения сохранены.',
    },
    api: {
      validation_error: 'Проверьте заполнение формы.',
      conflict: 'Данные устарели и были обновлены.',
      unauthorized: 'Войдите снова, чтобы продолжить.',
      forbidden: 'Для этого действия недостаточно прав.',
      not_found: 'Запись больше недоступна.',
      internal_error: 'Сервер временно недоступен.',
      fallback: 'Не удалось выполнить запрос. Попробуйте еще раз.',
    },
    enums: {
      status: {
        todo: 'Новая',
        in_progress: 'В работе',
        done: 'Готово',
        cancelled: 'Отменена',
      },
      type: {
        green: 'Зеленая',
        red: 'Красная',
      },
      invitationStatus: {
        pending: 'Ожидает',
        accepted: 'Принято',
        declined: 'Отклонено',
        revoked: 'Отозвано',
        expired: 'Истекло',
      },
      thresholdPreset: {
        day: 'День',
        week: 'Неделя',
        month: 'Месяц',
      },
      quickPreset: {
        '30m': '+30 мин',
        '1h': '+1 час',
        '3h': '+3 часа',
        '24h': '+24 часа',
      },
      yes: 'Да',
      no: 'Нет',
    },
    calendar: {
      title: 'Календарь',
      subtitle: 'План задач по времени с переносом и быстрым сдвигом.',
      rangeLabel: 'Диапазон',
      rangeDay: 'День',
      rangeWeek: 'Неделя',
      rangeMonth: 'Месяц',
      listTitle: 'Плановые задачи',
      listEmptyTitle: 'В выбранном диапазоне нет задач',
      listEmptyDescription: 'Когда у задач появится плановое время, они будут показаны здесь.',
      detailTitle: 'Карточка задачи',
      moveTitle: 'Перенос времени',
      moveAction: 'Перенести',
      quickRescheduleTitle: 'Быстрый перенос',
      movedNotice: 'Плановое время обновлено.',
      rescheduledNotice: 'Быстрый перенос выполнен.',
      priorityDecayApplied: 'Снижение приоритета применено.',
      missingSelection: 'Выберите задачу слева, чтобы увидеть детали и действия.',
    },
    sharing: {
      title: 'Доступ',
      subtitle: 'Приглашения и доступные вам цели или задачи.',
      inviteTitle: 'Новое приглашение',
      inviteTarget: 'Что открыть для доступа',
      inviteEmail: 'Электронная почта участника',
      inviteGoal: 'Цель',
      inviteTask: 'Задача',
      folderLabel: 'Папка',
      goalLabel: 'Цель',
      taskLabel: 'Задача',
      createInvite: 'Отправить приглашение',
      invitationListTitle: 'Приглашения',
      invitationsEmptyTitle: 'Приглашений пока нет',
      invitationsEmptyDescription: 'После отправки или получения приглашения оно появится здесь.',
      resourcesTitle: 'Общие ресурсы',
      sharedGoals: 'Общие цели',
      sharedTasks: 'Общие задачи',
      resourcesEmptyTitle: 'Общие ресурсы пока не обнаружены',
      resourcesEmptyDescription: 'После принятия инвайтов здесь появятся цели и задачи с доступом.',
      accept: 'Принять',
      decline: 'Отклонить',
      revoke: 'Отозвать',
      createdNotice: 'Инвайт отправлен.',
      updatedNotice: 'Статус инвайта обновлен.',
      targetHint: 'Можно открыть цель или отдельную задачу.',
      linkTitle: 'Ссылка доступа',
      linkAccept: 'Принять ссылку',
      linkAccepted: 'Доступ по ссылке принят.',
      linkHint: 'Ссылка найдена. После принятия ресурсы появятся в списке ниже.',
      pendingOnly: 'Действия доступны для ожидающих инвайтов.',
      sharedFolders: 'Общие папки',
      canCreateTasks: 'Можно создавать задачи',
      tokenMissing: 'Токен в ссылке не найден.',
      resourcesCount: 'ресурсов',
    },
    settings: {
      title: 'Настройки',
      subtitle: 'Язык интерфейса, уведомления и правила снижения приоритета владельца.',
      generalTitle: 'Общие настройки',
      policyTitle: 'Правила снижения приоритета',
      notificationsLabel: 'Уведомления',
      greenPolicy: 'Правило обычных задач',
      redPolicy: 'Правило важных задач',
      threshold: 'Порог',
      decayAmount: 'Снижение приоритета',
      syncHint: 'Сохраненный язык сразу синхронизируется с текущим языком веб-интерфейса.',
      saveAction: 'Сохранить настройки',
    },
    locale: {
      ru: 'Русский',
      en: 'Английский',
    },
  },
  en: {
    common: {
      title: 'Workspace',
      retry: 'Retry',
      refresh: 'Refresh',
      save: 'Save',
      create: 'Create',
      loadingTitle: 'Loading data',
      loadingDescription: 'Fetching current data.',
      errorTitle: 'Could not load data',
      errorDescription: 'Please check the connection and try again.',
      details: 'Details',
      version: 'Version',
      plannedTime: 'Planned',
      dueTime: 'Due',
      priority: 'Priority',
      status: 'Status',
      type: 'Type',
      goal: 'Goal',
      task: 'Task',
      openGoal: 'Open goal',
      openTask: 'Open task',
      noDescription: 'Description is empty so far.',
      share: 'Sharing',
      language: 'Language',
      enabled: 'Enabled',
      disabled: 'Disabled',
      conflictTitle: 'Version conflict detected',
      conflictDescription: 'The settings changed in another window. The latest version has been reloaded.',
      saved: 'Changes were saved.',
    },
    api: {
      validation_error: 'Please review the form fields.',
      conflict: 'The data was stale and has been refreshed.',
      unauthorized: 'Please sign in again to continue.',
      forbidden: 'You do not have permission for this action.',
      not_found: 'The record is no longer available.',
      internal_error: 'The server is temporarily unavailable.',
      fallback: 'Request failed. Please try again.',
    },
    enums: {
      status: {
        todo: 'Todo',
        in_progress: 'In progress',
        done: 'Done',
        cancelled: 'Cancelled',
      },
      type: {
        green: 'Green',
        red: 'Red',
      },
      invitationStatus: {
        pending: 'Pending',
        accepted: 'Accepted',
        declined: 'Declined',
        revoked: 'Revoked',
        expired: 'Expired',
      },
      thresholdPreset: {
        day: 'Day',
        week: 'Week',
        month: 'Month',
      },
      quickPreset: {
        '30m': '+30 min',
        '1h': '+1 hour',
        '3h': '+3 hours',
        '24h': '+24 hours',
      },
      yes: 'Yes',
      no: 'No',
    },
    calendar: {
      title: 'Calendar',
      subtitle: 'A time-based task plan with move and quick shift actions.',
      rangeLabel: 'Range',
      rangeDay: 'Day',
      rangeWeek: 'Week',
      rangeMonth: 'Month',
      listTitle: 'Scheduled tasks',
      listEmptyTitle: 'No tasks in this range',
      listEmptyDescription: 'Tasks appear here once they have a planned time.',
      detailTitle: 'Task card',
      moveTitle: 'Move time',
      moveAction: 'Move',
      quickRescheduleTitle: 'Quick reschedule',
      movedNotice: 'Planned time was updated.',
      rescheduledNotice: 'Quick reschedule completed.',
      priorityDecayApplied: 'Priority rules were applied.',
      missingSelection: 'Select a task on the left to see details and actions.',
    },
    sharing: {
      title: 'Sharing',
      subtitle: 'Invitations and shared goals or tasks.',
      inviteTitle: 'New invitation',
      inviteTarget: 'Resource to share',
      inviteEmail: 'Participant email',
      inviteGoal: 'Goal',
      inviteTask: 'Task',
      folderLabel: 'Folder',
      goalLabel: 'Goal',
      taskLabel: 'Task',
      createInvite: 'Send invitation',
      invitationListTitle: 'Invitations',
      invitationsEmptyTitle: 'No invitations yet',
      invitationsEmptyDescription: 'Sent or incoming invitations will appear here.',
      resourcesTitle: 'Shared resources',
      sharedGoals: 'Shared goals',
      sharedTasks: 'Shared tasks',
      resourcesEmptyTitle: 'No shared resources found yet',
      resourcesEmptyDescription: 'Accepted invitations will show shared goals and tasks here.',
      accept: 'Accept',
      decline: 'Decline',
      revoke: 'Revoke',
      createdNotice: 'Invitation sent.',
      updatedNotice: 'Invitation status updated.',
      targetHint: 'You can grant access to a goal or an individual task.',
      linkTitle: 'Share link',
      linkAccept: 'Accept link',
      linkAccepted: 'Share link accepted.',
      linkHint: 'Link found. After accepting it, resources appear below.',
      pendingOnly: 'Actions are available for pending invitations.',
      sharedFolders: 'Shared folders',
      canCreateTasks: 'Can create tasks',
      tokenMissing: 'No token was found in the link.',
      resourcesCount: 'resources',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Interface language, notifications, and owner priority rules.',
      generalTitle: 'General settings',
      policyTitle: 'Priority rules',
      notificationsLabel: 'Notifications',
      greenPolicy: 'Regular-task policy',
      redPolicy: 'Important-task policy',
      threshold: 'Threshold',
      decayAmount: 'Decay amount',
      syncHint: 'The saved language is synchronized with the current interface language immediately.',
      saveAction: 'Save settings',
    },
    locale: {
      ru: 'Russian',
      en: 'English',
    },
  },
} as const;

export function useAdvancedCopy() {
  const { locale } = useI18n();
  return advancedMessages[locale];
}
