import { useI18n } from '../../i18n';

const planningMessages = {
  ru: {
    common: {
      create: 'Создать',
      save: 'Сохранить',
      cancel: 'Отмена',
      edit: 'Изменить',
      archive: 'В архив',
      delete: 'Удалить',
      retry: 'Повторить',
      refresh: 'Обновить',
      share: 'Поделиться',
      details: 'Сведения',
      version: 'Версия',
      createdAt: 'Создано',
      updatedAt: 'Обновлено',
      conflictTitle: 'Данные изменились',
      conflictDescription: 'Откройте свежую версию и повторите действие.',
      loadingTitle: 'Загружаем план',
      loadingDescription: 'Получаем актуальные данные.',
      errorTitle: 'Не удалось загрузить план',
      errorDescription: 'Проверьте соединение и повторите запрос.',
      serverTrace: 'Код обращения',
      openGoals: 'Открыть цели',
      openTasks: 'Открыть задачи',
      noDescription: 'Без заметок.',
      activeSelection: 'Выбрано',
    },
    api: {
      validation_error: 'Проверьте заполнение формы.',
      conflict: 'Данные обновились. Повторите действие.',
      unauthorized: 'Сессия завершена.',
      forbidden: 'Недостаточно прав для действия.',
      not_found: 'Запись больше недоступна.',
      internal_error: 'Сервер временно недоступен.',
      fallback: 'Не удалось выполнить запрос. Попробуйте еще раз.',
    },
    folders: {
      title: 'Папки',
      subtitle: 'Рабочие папки.',
      listTitle: 'Папки',
      listEmptyTitle: 'Пока пусто',
      listEmptyDescription: 'Создайте папку, затем добавьте цель и задачи.',
      detailTitle: 'Папка',
      createTitle: 'Новая папка',
      editTitle: 'Изменение папки',
      name: 'Название',
      description: 'Заметки',
      displayOrder: 'Порядок',
      selectPrompt: 'Выберите папку.',
      archiveConfirm: 'Переместить папку в архив?',
      count: 'Папок',
    },
    goals: {
      title: 'Цели',
      subtitle: 'Цели внутри папки.',
      folderLabel: 'Папка',
      listTitle: 'Цели',
      listEmptyTitle: 'Добавьте цель',
      listEmptyDescription: 'У этой папки пока нет целей.',
      detailTitle: 'Цель',
      createTitle: 'Новая цель',
      editTitle: 'Изменение цели',
      name: 'Название',
      description: 'Заметки',
      selectFolderPrompt: 'Сначала выберите папку.',
      noFoldersTitle: 'Пока пусто',
      noFoldersDescription: 'Создайте папку, затем добавьте цель и задачи.',
      archiveConfirm: 'Переместить цель в архив?',
      shared: 'Общий доступ',
    },
    tasks: {
      title: 'План',
      subtitle: 'Папки, цели и задачи.',
      folderLabel: 'Папка',
      goalLabel: 'Цель',
      listTitle: 'План',
      listEmptyTitle: 'Пока пусто',
      listEmptyDescription: 'Создайте папку, затем добавьте цель и задачи.',
      detailTitle: 'Задача',
      createTitle: 'Новая задача',
      editTitle: 'Изменение задачи',
      titleLabel: 'Заголовок',
      descriptionLabel: 'Заметки',
      typeLabel: 'Тип',
      statusLabel: 'Статус',
      priorityLabel: 'Приоритет',
      plannedTimeLabel: 'Когда делать',
      dueTimeLabel: 'Дедлайн',
      tagsLabel: 'Теги',
      recurrenceLabel: 'Повтор',
      recurrenceEnabledLabel: 'Включить повтор',
      recurrenceActiveLabel: 'Повтор активен',
      recurrenceModeLabel: 'Режим повтора',
      recurrenceIntervalLabel: 'Интервал',
      recurrenceAnchorLabel: 'Опорное время',
      recurrenceWeekdaysLabel: 'Дни недели',
      recurrenceEndAtLabel: 'Окончание повтора',
      schedulingSectionTitle: 'Дополнительно',
      schedulingHelp: 'Повтор хранится вместе с задачей.',
      recurrenceHint: 'Для повтора нужно время "Когда делать" или дедлайн.',
      schedulingPartialSave: 'Задача сохранена, но часть дополнительных данных не применилась.',
      anchorPlanned: 'От времени "Когда делать"',
      anchorDue: 'От дедлайна',
      recurrenceModeDaily: 'Ежедневно',
      recurrenceModeWeekly: 'Еженедельно',
      recurrenceModeMonthly: 'Ежемесячно',
      weekdayMonday: 'Пн',
      weekdayTuesday: 'Вт',
      weekdayWednesday: 'Ср',
      weekdayThursday: 'Чт',
      weekdayFriday: 'Пт',
      weekdaySaturday: 'Сб',
      weekdaySunday: 'Вс',
      validationRequired: 'Поле обязательно.',
      validationPriorityRange: 'Укажите число от 1 до 10.',
      validationRecurrenceAnchor: 'Для повтора нужно время "Когда делать" или дедлайн.',
      validationRecurrenceInterval: 'Интервал должен быть не меньше 1.',
      validationRecurrenceWeekday: 'Нужен день недели опорного времени.',
      validationRecurrenceEndAt: 'Окончание должно быть позже начала.',
      noFoldersTitle: 'Пока пусто',
      noFoldersDescription: 'Создайте папку и цель.',
      noGoalsTitle: 'Добавьте цель',
      noGoalsDescription: 'У папки пока нет целей.',
      deleteConfirm: 'Удалить задачу?',
      recurrenceLater: 'Повтор не настроен.',
    },
    enums: {
      yes: 'Да',
      no: 'Нет',
      taskType: {
        green: 'Обычная',
        red: 'Важная',
      },
      taskStatus: {
        todo: 'Новая',
        in_progress: 'В работе',
        done: 'Готово',
        cancelled: 'Отменена',
      },
    },
  },
  en: {
    common: {
      create: 'Create',
      save: 'Save',
      cancel: 'Cancel',
      edit: 'Edit',
      archive: 'Archive',
      delete: 'Delete',
      retry: 'Retry',
      refresh: 'Refresh',
      share: 'Share',
      details: 'Details',
      version: 'Version',
      createdAt: 'Created',
      updatedAt: 'Updated',
      conflictTitle: 'Data changed',
      conflictDescription: 'Open the latest version and try again.',
      loadingTitle: 'Loading plan',
      loadingDescription: 'Fetching current data.',
      errorTitle: 'Could not load the plan',
      errorDescription: 'Check the connection and try again.',
      serverTrace: 'Reference code',
      openGoals: 'Open goals',
      openTasks: 'Open tasks',
      noDescription: 'No notes.',
      activeSelection: 'Selected',
    },
    api: {
      validation_error: 'Please review the form fields.',
      conflict: 'The data changed. Try again.',
      unauthorized: 'Signed out.',
      forbidden: 'You do not have permission for this action.',
      not_found: 'The record is no longer available.',
      internal_error: 'The server is temporarily unavailable.',
      fallback: 'Request failed. Please try again.',
    },
    folders: {
      title: 'Folders',
      subtitle: 'Workspace folders.',
      listTitle: 'Folders',
      listEmptyTitle: 'Nothing here yet',
      listEmptyDescription: 'Create a folder, then add a goal and tasks.',
      detailTitle: 'Folder',
      createTitle: 'New folder',
      editTitle: 'Edit folder',
      name: 'Name',
      description: 'Notes',
      displayOrder: 'Order',
      selectPrompt: 'Select a folder.',
      archiveConfirm: 'Archive this folder?',
      count: 'Folders',
    },
    goals: {
      title: 'Goals',
      subtitle: 'Goals inside a folder.',
      folderLabel: 'Folder',
      listTitle: 'Goals',
      listEmptyTitle: 'Add a goal',
      listEmptyDescription: 'This folder has no goals yet.',
      detailTitle: 'Goal',
      createTitle: 'New goal',
      editTitle: 'Edit goal',
      name: 'Name',
      description: 'Notes',
      selectFolderPrompt: 'Select a folder first.',
      noFoldersTitle: 'Nothing here yet',
      noFoldersDescription: 'Create a folder and goal.',
      archiveConfirm: 'Archive this goal?',
      shared: 'Shared',
    },
    tasks: {
      title: 'Plan',
      subtitle: 'Folders, goals, and tasks.',
      folderLabel: 'Folder',
      goalLabel: 'Goal',
      listTitle: 'Plan',
      listEmptyTitle: 'Nothing here yet',
      listEmptyDescription: 'Create a folder, then add a goal and tasks.',
      detailTitle: 'Task',
      createTitle: 'New task',
      editTitle: 'Edit task',
      titleLabel: 'Title',
      descriptionLabel: 'Notes',
      typeLabel: 'Type',
      statusLabel: 'Status',
      priorityLabel: 'Priority',
      plannedTimeLabel: 'Planned',
      dueTimeLabel: 'Due',
      tagsLabel: 'Tags',
      recurrenceLabel: 'Recurrence',
      recurrenceEnabledLabel: 'Enable recurrence',
      recurrenceActiveLabel: 'Recurrence active',
      recurrenceModeLabel: 'Recurrence mode',
      recurrenceIntervalLabel: 'Interval',
      recurrenceAnchorLabel: 'Anchor time',
      recurrenceWeekdaysLabel: 'Weekdays',
      recurrenceEndAtLabel: 'Recurrence end',
      schedulingSectionTitle: 'Details',
      schedulingHelp: 'Recurrence is saved with the task.',
      recurrenceHint: 'Recurrence needs planned or due time.',
      schedulingPartialSave: 'The task was saved, but some details were not applied.',
      anchorPlanned: 'From planned time',
      anchorDue: 'From due time',
      recurrenceModeDaily: 'Daily',
      recurrenceModeWeekly: 'Weekly',
      recurrenceModeMonthly: 'Monthly',
      weekdayMonday: 'Mon',
      weekdayTuesday: 'Tue',
      weekdayWednesday: 'Wed',
      weekdayThursday: 'Thu',
      weekdayFriday: 'Fri',
      weekdaySaturday: 'Sat',
      weekdaySunday: 'Sun',
      validationRequired: 'This field is required.',
      validationPriorityRange: 'Enter a number from 1 to 10.',
      validationRecurrenceAnchor: 'Recurrence needs planned or due time.',
      validationRecurrenceInterval: 'Interval must be at least 1.',
      validationRecurrenceWeekday: 'The anchor weekday is required.',
      validationRecurrenceEndAt: 'The end date must be later than the start.',
      noFoldersTitle: 'Nothing here yet',
      noFoldersDescription: 'Create a folder and goal.',
      noGoalsTitle: 'Add a goal',
      noGoalsDescription: 'This folder has no goals yet.',
      deleteConfirm: 'Delete this task?',
      recurrenceLater: 'Recurrence is not configured.',
    },
    enums: {
      yes: 'Yes',
      no: 'No',
      taskType: {
        green: 'Regular',
        red: 'Important',
      },
      taskStatus: {
        todo: 'Todo',
        in_progress: 'In progress',
        done: 'Done',
        cancelled: 'Cancelled',
      },
    },
  },
} as const;

export function usePlanningCopy() {
  const { locale } = useI18n();
  return planningMessages[locale];
}
