import { useI18n } from '../../i18n';

const planningMessages = {
  ru: {
    common: {
      create: 'Создать',
      save: 'Сохранить',
      cancel: 'Отмена',
      edit: 'Изменить',
      archive: 'В архив',
      delete: 'Удалить',
      retry: 'Повторить',
      refresh: 'Обновить',
      details: 'Детали',
      version: 'Версия',
      createdAt: 'Создано',
      updatedAt: 'Обновлено',
      conflictTitle: 'Обнаружен конфликт версии',
      conflictDescription:
        'Пока форма была открыта, запись изменилась в другом сеансе. Мы подтянули свежую версию, чтобы вы могли продолжить без потери контекста.',
      loadingTitle: 'Загрузка рабочей области',
      loadingDescription: 'Запрашиваем актуальные данные планирования и синхронизируем выбор.',
      errorTitle: 'Не удалось загрузить данные',
      errorDescription: 'Проверьте соединение и повторите запрос.',
      serverTrace: 'Trace ID',
      openGoals: 'Открыть цели',
      openTasks: 'Открыть задачи',
      noDescription: 'Описание пока не заполнено.',
      activeSelection: 'Активный выбор',
    },
    api: {
      validation_error: 'Проверьте заполнение формы.',
      conflict: 'Данные устарели и были обновлены.',
      unauthorized: 'Сеанс больше не действителен.',
      forbidden: 'Для этого действия недостаточно прав.',
      not_found: 'Запись уже недоступна.',
      internal_error: 'Сервер временно недоступен.',
      fallback: 'Не удалось выполнить запрос. Попробуйте еще раз.',
    },
    folders: {
      title: 'Папки',
      subtitle: 'Список рабочих папок с быстрым созданием, редактированием и архивированием.',
      listTitle: 'Список папок',
      listEmptyTitle: 'Папок пока нет',
      listEmptyDescription: 'Создайте первую папку, чтобы собирать в ней цели и связанные задачи.',
      detailTitle: 'Карточка папки',
      createTitle: 'Новая папка',
      editTitle: 'Изменение папки',
      name: 'Название',
      description: 'Описание',
      displayOrder: 'Порядок',
      selectPrompt: 'Выберите папку слева или создайте новую.',
      archiveConfirm: 'Переместить папку в архив?',
      count: 'Папок',
    },
    goals: {
      title: 'Цели',
      subtitle: 'Цели внутри выбранной папки с детальной карточкой и архивированием без смены shell.',
      folderLabel: 'Папка',
      listTitle: 'Цели папки',
      listEmptyTitle: 'В этой папке пока нет целей',
      listEmptyDescription: 'Добавьте первую цель, чтобы перейти к задачам и срокам.',
      detailTitle: 'Карточка цели',
      createTitle: 'Новая цель',
      editTitle: 'Изменение цели',
      name: 'Название',
      description: 'Описание',
      selectFolderPrompt: 'Сначала выберите папку.',
      noFoldersTitle: 'Нужна хотя бы одна папка',
      noFoldersDescription: 'Сначала создайте папку, затем здесь появятся связанные с ней цели.',
      archiveConfirm: 'Переместить цель в архив?',
      shared: 'Совместный доступ',
    },
    tasks: {
      title: 'Задачи',
      subtitle: 'Задачи выбранной цели с карточкой, редактированием статуса и удалением.',
      folderLabel: 'Папка',
      goalLabel: 'Цель',
      listTitle: 'Задачи цели',
      listEmptyTitle: 'У выбранной цели пока нет задач',
      listEmptyDescription: 'Создайте первую задачу, чтобы зафиксировать статус, приоритет и сроки.',
      detailTitle: 'Карточка задачи',
      createTitle: 'Новая задача',
      editTitle: 'Изменение задачи',
      titleLabel: 'Заголовок',
      descriptionLabel: 'Описание',
      typeLabel: 'Тип',
      statusLabel: 'Статус',
      priorityLabel: 'Приоритет',
      plannedTimeLabel: 'План',
      dueTimeLabel: 'Срок',
      tagsLabel: 'Теги',
      recurrenceLabel: 'Повтор',
      remindersLabel: 'Напоминания',
      recurrenceEnabledLabel: 'Включить повтор',
      recurrenceActiveLabel: 'Повтор активен',
      recurrenceModeLabel: 'Режим повтора',
      recurrenceIntervalLabel: 'Интервал',
      recurrenceAnchorLabel: 'Якорное время',
      recurrenceWeekdaysLabel: 'Дни недели',
      recurrenceEndAtLabel: 'Окончание повтора',
      reminderModeLabel: 'Режим напоминания',
      reminderOffsetLabel: 'За сколько минут',
      reminderActiveLabel: 'Напоминание активно',
      reminderAdd: 'Добавить напоминание',
      reminderRemove: 'Убрать',
      schedulingSectionTitle: 'Расписание',
      schedulingHelp: 'Повторы и напоминания сохраняются после основной карточки задачи и используют planned/due time как anchor.',
      recurrenceHint: 'Для повтора нужен planned или due time. Weekly mode должен включать owner-local день anchor-времени.',
      remindersHint: 'Напоминания заменяются полным списком. Пустой список очищает все reminder rules.',
      anchorPlanned: 'От planned time',
      anchorDue: 'От due time',
      recurrenceModeDaily: 'Ежедневно',
      recurrenceModeWeekly: 'Еженедельно',
      recurrenceModeMonthly: 'Ежемесячно',
      reminderModeBeforePlanned: 'До planned time',
      reminderModeBeforeDue: 'До due time',
      weekdayMonday: 'Пн',
      weekdayTuesday: 'Вт',
      weekdayWednesday: 'Ср',
      weekdayThursday: 'Чт',
      weekdayFriday: 'Пт',
      weekdaySaturday: 'Сб',
      weekdaySunday: 'Вс',
      validationRequired: 'Поле обязательно.',
      validationPriorityRange: 'Укажите число от 1 до 10.',
      validationRecurrenceAnchor: 'Для повтора нужен planned или due time.',
      validationRecurrenceInterval: 'Интервал повтора должен быть не меньше 1.',
      validationRecurrenceWeekday: 'Weekly repeat должен включать anchor weekday.',
      validationRecurrenceEndAt: 'Дата окончания должна быть позже anchor time.',
      validationReminderOffset: 'Сдвиг напоминания должен быть не меньше 1 минуты.',
      validationReminderDuplicate: 'Нельзя дублировать одинаковые reminder mode + offset.',
      validationReminderAnchor: 'Выбранный reminder mode требует соответствующее planned/due time.',
      noFoldersTitle: 'Нужна папка и цель',
      noFoldersDescription: 'Сначала создайте папку и цель, затем здесь откроется управление задачами.',
      noGoalsTitle: 'У папки пока нет целей',
      noGoalsDescription: 'Перейдите к целям и добавьте хотя бы одну, чтобы планировать задачи.',
      deleteConfirm: 'Удалить задачу из текущего списка?',
      recurrenceLater: 'Повтор пока не настроен.',
      remindersLater: 'Напоминания пока не настроены.',
    },
    enums: {
      yes: 'Да',
      no: 'Нет',
      taskType: {
        green: 'Зеленая',
        red: 'Красная',
      },
      taskStatus: {
        todo: 'Новая',
        in_progress: 'В работе',
        done: 'Готово',
        cancelled: 'Отменена',
      },
    },
  },
  en: {
    common: {
      create: 'Create',
      save: 'Save',
      cancel: 'Cancel',
      edit: 'Edit',
      archive: 'Archive',
      delete: 'Delete',
      retry: 'Retry',
      refresh: 'Refresh',
      details: 'Details',
      version: 'Version',
      createdAt: 'Created',
      updatedAt: 'Updated',
      conflictTitle: 'Version conflict detected',
      conflictDescription:
        'The record changed in another session while this form was open. The latest server copy has been reloaded so you can keep working.',
      loadingTitle: 'Loading workspace',
      loadingDescription: 'Fetching current planning data and synchronizing the active selection.',
      errorTitle: 'Could not load data',
      errorDescription: 'Please check the connection and try again.',
      serverTrace: 'Trace ID',
      openGoals: 'Open goals',
      openTasks: 'Open tasks',
      noDescription: 'Description is empty so far.',
      activeSelection: 'Active selection',
    },
    api: {
      validation_error: 'Please review the form fields.',
      conflict: 'The data was stale and has been refreshed.',
      unauthorized: 'The session is no longer valid.',
      forbidden: 'You do not have permission for this action.',
      not_found: 'The record is no longer available.',
      internal_error: 'The server is temporarily unavailable.',
      fallback: 'Request failed. Please try again.',
    },
    folders: {
      title: 'Folders',
      subtitle: 'Workspace folders with quick create, edit, and archive interactions.',
      listTitle: 'Folder list',
      listEmptyTitle: 'No folders yet',
      listEmptyDescription: 'Create your first folder to group related goals and tasks.',
      detailTitle: 'Folder card',
      createTitle: 'New folder',
      editTitle: 'Edit folder',
      name: 'Name',
      description: 'Description',
      displayOrder: 'Order',
      selectPrompt: 'Select a folder on the left or create a new one.',
      archiveConfirm: 'Move this folder to the archive?',
      count: 'Folders',
    },
    goals: {
      title: 'Goals',
      subtitle: 'Goals inside the selected folder with detail cards and archive actions.',
      folderLabel: 'Folder',
      listTitle: 'Folder goals',
      listEmptyTitle: 'No goals in this folder yet',
      listEmptyDescription: 'Add the first goal to move from structure into concrete task planning.',
      detailTitle: 'Goal card',
      createTitle: 'New goal',
      editTitle: 'Edit goal',
      name: 'Name',
      description: 'Description',
      selectFolderPrompt: 'Select a folder first.',
      noFoldersTitle: 'At least one folder is required',
      noFoldersDescription: 'Create a folder first, then its goals will appear here.',
      archiveConfirm: 'Move this goal to the archive?',
      shared: 'Shared',
    },
    tasks: {
      title: 'Tasks',
      subtitle: 'Tasks for the selected goal with detail, status editing, and delete actions.',
      folderLabel: 'Folder',
      goalLabel: 'Goal',
      listTitle: 'Goal tasks',
      listEmptyTitle: 'No tasks for this goal yet',
      listEmptyDescription: 'Create the first task to capture status, priority, and timing.',
      detailTitle: 'Task card',
      createTitle: 'New task',
      editTitle: 'Edit task',
      titleLabel: 'Title',
      descriptionLabel: 'Description',
      typeLabel: 'Type',
      statusLabel: 'Status',
      priorityLabel: 'Priority',
      plannedTimeLabel: 'Planned',
      dueTimeLabel: 'Due',
      tagsLabel: 'Tags',
      recurrenceLabel: 'Recurrence',
      remindersLabel: 'Reminders',
      recurrenceEnabledLabel: 'Enable recurrence',
      recurrenceActiveLabel: 'Recurrence active',
      recurrenceModeLabel: 'Recurrence mode',
      recurrenceIntervalLabel: 'Interval',
      recurrenceAnchorLabel: 'Anchor time',
      recurrenceWeekdaysLabel: 'Weekdays',
      recurrenceEndAtLabel: 'Recurrence end',
      reminderModeLabel: 'Reminder mode',
      reminderOffsetLabel: 'Minutes before',
      reminderActiveLabel: 'Reminder active',
      reminderAdd: 'Add reminder',
      reminderRemove: 'Remove',
      schedulingSectionTitle: 'Scheduling',
      schedulingHelp: 'Recurrence and reminders are saved after the base task card and use planned/due time as the anchor.',
      recurrenceHint: 'Recurrence needs a planned or due time. Weekly mode must include the owner-local anchor weekday.',
      remindersHint: 'Reminders are replaced as a full list. An empty list clears all reminder rules.',
      anchorPlanned: 'From planned time',
      anchorDue: 'From due time',
      recurrenceModeDaily: 'Daily',
      recurrenceModeWeekly: 'Weekly',
      recurrenceModeMonthly: 'Monthly',
      reminderModeBeforePlanned: 'Before planned time',
      reminderModeBeforeDue: 'Before due time',
      weekdayMonday: 'Mon',
      weekdayTuesday: 'Tue',
      weekdayWednesday: 'Wed',
      weekdayThursday: 'Thu',
      weekdayFriday: 'Fri',
      weekdaySaturday: 'Sat',
      weekdaySunday: 'Sun',
      validationRequired: 'This field is required.',
      validationPriorityRange: 'Enter a number from 1 to 10.',
      validationRecurrenceAnchor: 'Recurrence needs planned or due time.',
      validationRecurrenceInterval: 'Recurrence interval must be at least 1.',
      validationRecurrenceWeekday: 'Weekly recurrence must include the anchor weekday.',
      validationRecurrenceEndAt: 'The end date must be later than the anchor time.',
      validationReminderOffset: 'Reminder offset must be at least 1 minute.',
      validationReminderDuplicate: 'Duplicate reminder mode + offset combinations are not allowed.',
      validationReminderAnchor: 'The selected reminder mode requires matching planned/due time.',
      noFoldersTitle: 'A folder and goal are required',
      noFoldersDescription: 'Create a folder and goal first, then task management opens here.',
      noGoalsTitle: 'This folder has no goals yet',
      noGoalsDescription: 'Open the goals screen and add one before planning tasks.',
      deleteConfirm: 'Delete this task from the current list?',
      recurrenceLater: 'Recurrence is not configured yet.',
      remindersLater: 'Reminders are not configured yet.',
    },
    enums: {
      yes: 'Yes',
      no: 'No',
      taskType: {
        green: 'Green',
        red: 'Red',
      },
      taskStatus: {
        todo: 'Todo',
        in_progress: 'In progress',
        done: 'Done',
        cancelled: 'Cancelled',
      },
    },
  },
} as const;

export function usePlanningCopy() {
  const { locale } = useI18n();
  return planningMessages[locale];
}
