package com.rocketflow.companion.auth

data class AuthCopy(
    val title: String,
    val subtitle: String,
    val email: String,
    val password: String,
    val login: String,
    val restore: String,
    val logout: String,
    val loading: String,
    val ready: String,
    val nextSurfaces: String,
    val sessionLabel: String,
    val timezoneLabel: String,
    val expiresAtLabel: String,
    val noSession: String,
    val loginRequired: String,
    val browseTitle: String,
    val planningTitle: String,
    val foldersTitle: String,
    val goalsTitle: String,
    val tasksTitle: String,
    val sharedGoalsTitle: String,
    val sharedTasksTitle: String,
    val noFolders: String,
    val noGoals: String,
    val noTasks: String,
    val detailTitle: String,
    val detailEmpty: String,
    val detailLoading: String,
    val tagsTitle: String,
    val recurrenceTitle: String,
    val remindersTitle: String,
    val sharedLabel: String,
    val archivedLabel: String,
    val statusLabel: String,
    val typeLabel: String,
    val priorityLabel: String,
    val plannedTimeLabel: String,
    val dueTimeLabel: String,
    val platformLabel: String,
    val createdAtLabel: String,
    val activeLabel: String,
    val yes: String,
    val no: String,
    val none: String,
    val notificationsTitle: String,
    val pushToken: String,
    val pushTokenUpdatedAt: String,
    val pushTokenMissing: String,
    val pushTokenRefresh: String,
    val firebaseUnavailable: String,
    val deviceName: String,
    val registerDevice: String,
    val unregisterDevice: String,
    val currentDevice: String,
    val noRegisteredDevice: String,
    val deepLinkTitle: String,
    val deepLinkPending: String,
    val deepLinkOpened: String,
    val pushTokenRequired: String,
    val notificationPermissionRequired: String,
    val notificationPermissionAction: String,
    val browseLater: String,
    val detailLater: String,
    val pushLater: String,
    val languageRussian: String,
    val languageEnglish: String,
    val languageRussianA11y: String,
    val languageEnglishA11y: String,
    val planningOffline: String,
    val planningSynced: String,
    val planningPending: String,
    val syncAction: String,
    val addFolderAction: String,
    val addGoalAction: String,
    val addTaskAction: String,
    val editAction: String,
    val deleteAction: String,
    val cancelAction: String,
    val saveAction: String,
    val deleteConfirmAction: String,
    val addFolderTitle: String,
    val editFolderTitle: String,
    val addGoalTitle: String,
    val editGoalTitle: String,
    val addTaskTitle: String,
    val editTaskTitle: String,
    val deleteFolderTitle: String,
    val deleteGoalTitle: String,
    val deleteTaskTitle: String,
    val nameField: String,
    val descriptionField: String,
    val titleField: String,
    val typeField: String,
    val statusField: String,
    val priorityField: String,
    val plannedTimeField: String,
    val dueTimeField: String,
    val folderNameRequired: String,
    val goalNameRequired: String,
    val taskTitleRequired: String,
    val taskTypeRequired: String,
    val taskStatusRequired: String,
    val taskPriorityRequired: String,
    val savedOffline: String,
    val syncErrorLabel: String,
    val traceIdLabel: String,
    val requestFailed: String,
    val priorityShort: String,
    val statusTodo: String,
    val statusInProgress: String,
    val statusDone: String,
    val statusCancelled: String,
    val typeGreen: String,
    val typeRed: String
)

fun authCopy(language: String?): AuthCopy {
    val isEnglish = language?.startsWith("en", ignoreCase = true) == true

    return if (isEnglish) {
        AuthCopy(
            title = "RocketFlow",
            subtitle = "Folders, goals, and tasks in one quiet workspace.",
            email = "Email",
            password = "Password",
            login = "Sign in",
            restore = "Refresh",
            logout = "Sign out",
            loading = "Loading...",
            ready = "Synced",
            nextSurfaces = "Plan",
            sessionLabel = "Account",
            timezoneLabel = "Timezone",
            expiresAtLabel = "Sign-in valid until",
            noSession = "Sign in required",
            loginRequired = "Sign in to open your workspace.",
            browseTitle = "Workspace",
            planningTitle = "Planning",
            foldersTitle = "Folders",
            goalsTitle = "Goals",
            tasksTitle = "Tasks",
            sharedGoalsTitle = "Shared goals",
            sharedTasksTitle = "Shared tasks",
            noFolders = "No folders yet.",
            noGoals = "No goals yet.",
            noTasks = "No tasks yet.",
            detailTitle = "Task detail",
            detailEmpty = "Select a task.",
            detailLoading = "Opening...",
            tagsTitle = "Tags",
            recurrenceTitle = "Recurrence",
            remindersTitle = "Reminders",
            sharedLabel = "Shared",
            archivedLabel = "Archived",
            statusLabel = "Status",
            typeLabel = "Type",
            priorityLabel = "Priority",
            plannedTimeLabel = "Planned",
            dueTimeLabel = "Due",
            platformLabel = "Platform",
            createdAtLabel = "Created",
            activeLabel = "Active",
            yes = "Yes",
            no = "No",
            none = "None",
            notificationsTitle = "Sync",
            pushToken = "Notification status",
            pushTokenUpdatedAt = "Updated",
            pushTokenMissing = "Notifications are not ready yet.",
            pushTokenRefresh = "Refresh",
            firebaseUnavailable = "Notifications are not available on this device.",
            deviceName = "Device name",
            registerDevice = "Connect this phone",
            unregisterDevice = "Disconnect this phone",
            currentDevice = "Connected phone",
            noRegisteredDevice = "No phone connected.",
            deepLinkTitle = "Notification open",
            deepLinkPending = "Pending task open after sign-in",
            deepLinkOpened = "Opened task from notification",
            pushTokenRequired = "Notifications must be ready before connecting this phone.",
            notificationPermissionRequired = "Allow notifications for reminders.",
            notificationPermissionAction = "Enable notifications",
            browseLater = "Browse is active.",
            detailLater = "Task detail is active.",
            pushLater = "Notification delivery is not ready yet.",
            languageRussian = "RU",
            languageEnglish = "EN",
            languageRussianA11y = "Switch language to Russian",
            languageEnglishA11y = "Switch language to English",
            planningOffline = "Offline cache",
            planningSynced = "Synced",
            planningPending = "pending",
            syncAction = "Sync",
            addFolderAction = "Add",
            addGoalAction = "Add",
            addTaskAction = "Add",
            editAction = "Edit",
            deleteAction = "Delete",
            cancelAction = "Cancel",
            saveAction = "Save",
            deleteConfirmAction = "Delete",
            addFolderTitle = "Add folder",
            editFolderTitle = "Edit folder",
            addGoalTitle = "Add goal",
            editGoalTitle = "Edit goal",
            addTaskTitle = "Add task",
            editTaskTitle = "Edit task",
            deleteFolderTitle = "Delete folder?",
            deleteGoalTitle = "Delete goal?",
            deleteTaskTitle = "Delete task?",
            nameField = "Name",
            descriptionField = "Description",
            titleField = "Title",
            typeField = "Type: green/red",
            statusField = "Status",
            priorityField = "Priority 1..10",
            plannedTimeField = "Planned time",
            dueTimeField = "Due time",
            folderNameRequired = "Folder name is required.",
            goalNameRequired = "Goal name is required.",
            taskTitleRequired = "Task title is required.",
            taskTypeRequired = "Choose a type.",
            taskStatusRequired = "Choose a status.",
            taskPriorityRequired = "Priority must be from 1 to 10.",
            savedOffline = "Saved offline",
            syncErrorLabel = "Sync error",
            traceIdLabel = "Error code",
            requestFailed = "Request failed.",
            priorityShort = "P",
            statusTodo = "To do",
            statusInProgress = "In progress",
            statusDone = "Done",
            statusCancelled = "Cancelled",
            typeGreen = "Green",
            typeRed = "Red"
        )
    } else {
        AuthCopy(
            title = "RocketFlow",
            subtitle = "Папки, цели и задачи в одном спокойном месте.",
            email = "Email",
            password = "Пароль",
            login = "Войти",
            restore = "Обновить",
            logout = "Выйти",
            loading = "Загрузка...",
            ready = "Синхронизировано",
            nextSurfaces = "План",
            sessionLabel = "Аккаунт",
            timezoneLabel = "Часовой пояс",
            expiresAtLabel = "Вход действует до",
            noSession = "Нужен вход",
            loginRequired = "Войдите, чтобы открыть рабочее место.",
            browseTitle = "Рабочее место",
            planningTitle = "Планирование",
            foldersTitle = "Папки",
            goalsTitle = "Цели",
            tasksTitle = "Задачи",
            sharedGoalsTitle = "Общие цели",
            sharedTasksTitle = "Общие задачи",
            noFolders = "Папок пока нет.",
            noGoals = "Целей пока нет.",
            noTasks = "Задач пока нет.",
            detailTitle = "Детали задачи",
            detailEmpty = "Выберите задачу.",
            detailLoading = "Открытие...",
            tagsTitle = "Теги",
            recurrenceTitle = "Повтор",
            remindersTitle = "Напоминания",
            sharedLabel = "Общее",
            archivedLabel = "В архиве",
            statusLabel = "Статус",
            typeLabel = "Тип",
            priorityLabel = "Приоритет",
            plannedTimeLabel = "План",
            dueTimeLabel = "Срок",
            platformLabel = "Платформа",
            createdAtLabel = "Создано",
            activeLabel = "Активно",
            yes = "Да",
            no = "Нет",
            none = "Нет",
            notificationsTitle = "Синхронизация",
            pushToken = "Статус уведомлений",
            pushTokenUpdatedAt = "Обновлено",
            pushTokenMissing = "Уведомления пока не готовы.",
            pushTokenRefresh = "Обновить",
            firebaseUnavailable = "Уведомления недоступны на этом устройстве.",
            deviceName = "Имя устройства",
            registerDevice = "Подключить телефон",
            unregisterDevice = "Отключить телефон",
            currentDevice = "Подключенный телефон",
            noRegisteredDevice = "Телефон не подключен.",
            deepLinkTitle = "Открытие уведомления",
            deepLinkPending = "Задача откроется после входа",
            deepLinkOpened = "Задача открыта из уведомления",
            pushTokenRequired = "Сначала подготовьте уведомления.",
            notificationPermissionRequired = "Разрешите уведомления для напоминаний.",
            notificationPermissionAction = "Включить уведомления",
            browseLater = "Обзор активен.",
            detailLater = "Детали задачи активны.",
            pushLater = "Доставка уведомлений пока не готова.",
            languageRussian = "RU",
            languageEnglish = "EN",
            languageRussianA11y = "Переключить язык на русский",
            languageEnglishA11y = "Переключить язык на английский",
            planningOffline = "Офлайн-кэш",
            planningSynced = "Синхронизировано",
            planningPending = "ожидает",
            syncAction = "Синхронизировать",
            addFolderAction = "Добавить",
            addGoalAction = "Добавить",
            addTaskAction = "Добавить",
            editAction = "Изменить",
            deleteAction = "Удалить",
            cancelAction = "Отмена",
            saveAction = "Сохранить",
            deleteConfirmAction = "Удалить",
            addFolderTitle = "Добавить папку",
            editFolderTitle = "Изменить папку",
            addGoalTitle = "Добавить цель",
            editGoalTitle = "Изменить цель",
            addTaskTitle = "Добавить задачу",
            editTaskTitle = "Изменить задачу",
            deleteFolderTitle = "Удалить папку?",
            deleteGoalTitle = "Удалить цель?",
            deleteTaskTitle = "Удалить задачу?",
            nameField = "Название",
            descriptionField = "Описание",
            titleField = "Заголовок",
            typeField = "Тип: green/red",
            statusField = "Статус",
            priorityField = "Приоритет 1..10",
            plannedTimeField = "Плановое время",
            dueTimeField = "Срок",
            folderNameRequired = "Введите название папки.",
            goalNameRequired = "Введите название цели.",
            taskTitleRequired = "Введите заголовок задачи.",
            taskTypeRequired = "Выберите тип.",
            taskStatusRequired = "Выберите статус.",
            taskPriorityRequired = "Приоритет должен быть от 1 до 10.",
            savedOffline = "Сохранено офлайн",
            syncErrorLabel = "Ошибка синхронизации",
            traceIdLabel = "Код ошибки",
            requestFailed = "Запрос не выполнен.",
            priorityShort = "П",
            statusTodo = "К выполнению",
            statusInProgress = "В работе",
            statusDone = "Готово",
            statusCancelled = "Отменено",
            typeGreen = "Зеленая",
            typeRed = "Красная"
        )
    }
}
