package com.rocketflow.companion.auth

import java.util.Locale

data class AuthCopy(
    val title: String,
    val subtitle: String,
    val email: String,
    val password: String,
    val login: String,
    val restore: String,
    val logout: String,
    val loading: String,
    val ready: String,
    val nextSurfaces: String,
    val sessionLabel: String,
    val timezoneLabel: String,
    val expiresAtLabel: String,
    val noSession: String,
    val loginRequired: String,
    val browseTitle: String,
    val foldersTitle: String,
    val goalsTitle: String,
    val tasksTitle: String,
    val sharedGoalsTitle: String,
    val sharedTasksTitle: String,
    val noFolders: String,
    val noGoals: String,
    val noTasks: String,
    val detailTitle: String,
    val detailEmpty: String,
    val detailLoading: String,
    val tagsTitle: String,
    val recurrenceTitle: String,
    val remindersTitle: String,
    val sharedLabel: String,
    val archivedLabel: String,
    val none: String,
    val notificationsTitle: String,
    val pushToken: String,
    val deviceName: String,
    val registerDevice: String,
    val unregisterDevice: String,
    val currentDevice: String,
    val noRegisteredDevice: String,
    val deepLinkTitle: String,
    val deepLinkPending: String,
    val deepLinkOpened: String,
    val pushTokenRequired: String,
    val browseLater: String,
    val detailLater: String,
    val pushLater: String
)

fun authCopy(language: String?): AuthCopy {
    val isEnglish = (language ?: Locale.getDefault().language).startsWith("en")

    return if (isEnglish) {
        AuthCopy(
            title = "RocketFlow Companion",
            subtitle = "Auth, browse, notification registration, and task open foundation for the Android MVP companion.",
            email = "Email",
            password = "Password",
            login = "Sign in",
            restore = "Refresh",
            logout = "Sign out",
            loading = "Loading...",
            ready = "Session active",
            nextSurfaces = "Next companion surfaces",
            sessionLabel = "Signed in as",
            timezoneLabel = "Timezone",
            expiresAtLabel = "Token expires",
            noSession = "No active session",
            loginRequired = "Sign in to restore the companion workspace.",
            browseTitle = "Owned and shared browse",
            foldersTitle = "Folders",
            goalsTitle = "Goals",
            tasksTitle = "Tasks",
            sharedGoalsTitle = "Shared goals",
            sharedTasksTitle = "Shared tasks",
            noFolders = "No owned folders yet.",
            noGoals = "No goals in this folder yet.",
            noTasks = "No tasks in this goal yet.",
            detailTitle = "Task detail",
            detailEmpty = "Select a task from owned or shared lists to open read-only detail.",
            detailLoading = "Loading task detail...",
            tagsTitle = "Tags",
            recurrenceTitle = "Recurrence",
            remindersTitle = "Reminders",
            sharedLabel = "Shared",
            archivedLabel = "Archived",
            none = "None",
            notificationsTitle = "Push registration",
            pushToken = "Push token",
            deviceName = "Device name",
            registerDevice = "Register device",
            unregisterDevice = "Deactivate device",
            currentDevice = "Current device registration",
            noRegisteredDevice = "No stored device registration yet.",
            deepLinkTitle = "Notification open",
            deepLinkPending = "Pending task open after sign-in",
            deepLinkOpened = "Opened task from notification / deep link",
            pushTokenRequired = "Push token is required before device registration.",
            browseLater = "Owned and shared browse are active.",
            detailLater = "Read-only task detail is active and now supports notification-open entry.",
            pushLater = "Real FCM delivery stays behind later staging credential rollout gates."
        )
    } else {
        AuthCopy(
            title = "RocketFlow Companion",
            subtitle = "Android companion dlia auth, browse, push registration i notification-open foundation v ramkakh MVP.",
            email = "Email",
            password = "Parol",
            login = "Voiti",
            restore = "Obnovit",
            logout = "Vyiti",
            loading = "Zagruzka...",
            ready = "Seans aktiven",
            nextSurfaces = "Sleduiushchie companion-poverkhnosti",
            sessionLabel = "Seans",
            timezoneLabel = "Chasovoi poias",
            expiresAtLabel = "Token istekaet",
            noSession = "Aktivnogo seansa net",
            loginRequired = "Voidite, chtoby vosstanovit companion workspace.",
            browseTitle = "Owned i shared browse",
            foldersTitle = "Papki",
            goalsTitle = "Tseli",
            tasksTitle = "Zadachi",
            sharedGoalsTitle = "Shared goals",
            sharedTasksTitle = "Shared tasks",
            noFolders = "Sobstvennykh papok poka net.",
            noGoals = "V etoi papke poka net tselei.",
            noTasks = "V etoi tseli poka net zadach.",
            detailTitle = "Task detail",
            detailEmpty = "Vyberite zadachu iz owned ili shared spiskov, chtoby otkryt read-only detail.",
            detailLoading = "Zagruzhaem task detail...",
            tagsTitle = "Tegi",
            recurrenceTitle = "Povtor",
            remindersTitle = "Napominaniia",
            sharedLabel = "Sovmestno",
            archivedLabel = "V arkhive",
            none = "Net",
            notificationsTitle = "Push registration",
            pushToken = "Push token",
            deviceName = "Nazvanie ustroistva",
            registerDevice = "Zaregistrirovat ustroistvo",
            unregisterDevice = "Deaktivirovat ustroistvo",
            currentDevice = "Tekushchaia registratsiia ustroistva",
            noRegisteredDevice = "Sokhranennoy registratsii ustroistva poka net.",
            deepLinkTitle = "Notification open",
            deepLinkPending = "Ozhidaet otkrytiia zadachi posle vhoda",
            deepLinkOpened = "Zadacha otkryta iz notification / deep link",
            pushTokenRequired = "Pered registratsiei ustroistva nuzhen push token.",
            browseLater = "Owned i shared browse uzhe aktivny.",
            detailLater = "Read-only task detail uzhe aktivny i teper podderzhivaet notification-open entry.",
            pushLater = "Real FCM delivery ostaiotsia za pozdnim staging credential rollout gate."
        )
    }
}
